### ISSUE TITLE
“broker发送tps”的表盘是不是不对呀？测试时候有的数据甚至达到100k+ tps

### ISSUE THREAD

**Issue by cxposition** [xxd763795151/rocketmq-monitor#3]

**Comment by xxd763795151** [comment]
> _No description provided._

应该是没问题的，因为以前经常用的。要么就是实际发送数据确实达到这个量了，或者用的rocketmq-exporter的这个指标是不是比以前改进了，另外在面板上，这个指标应该是不计算的，直接拿原始数据展示的吧

**Comment by cxposition** [comment]
> 因为这个数据和rocketmq-console有较大差距，有可能是rocketmq-console有问题，昨天也看到了这个表盘是拿rocketmq-exporter这个指标的原始数据

**Comment by cxposition** [comment]
还有一个问题就是“消费端运行状态”这个模块里面拿不到数据，我看里面的指标大多是直接取原数据的并没有进行计算，这是哪里出了问题呢？

**Comment by cxposition** [comment]
比如说 消费端拉取tps（rocketmq_client_consumer_push_tps），消费端消费成功tps(rocketmq_client_consume_ok_msg_tps)、消费端消费平均耗时(rocketmq_client_consume_rt)这些指标都没有数据

**Comment by xxd763795151** [comment]
> 

就直接查看rocketmq-exporter的web接口，这几个指标是否有数据。如果没有的话，看下是不是没有消费端在运行的原因

**Comment by cxposition** [comment]
喔喔，行，多谢
